#Broadcasting

In [2]:
import numpy as np
var1 = np.array([[1],[2],[3]])
var2 = np.array([ 4,5,6])
print(var1 + var2)

[[5 6 7]
 [6 7 8]
 [7 8 9]]


In [5]:
x = np.array([[1],[2]])
y = np.array([[1,2,3],[4,5,6]])

print(x+y)


[[2 3 4]
 [6 7 8]]


#slicing

In [12]:
x = np.array([5,15,10,20,30])
x[1:4]
x[1:]
x[:4]
x[::2]

array([ 5, 10, 30])

In [15]:
y = np.array([[9,8,7,6,],[11,12,13,14]])
print(y)
y[0,1:4]

[[ 9  8  7  6]
 [11 12 13 14]]


array([8, 7, 6])

#iteration 3D array

In [18]:
var_arr = np.array([[[1,2,3,4],[5,6,7,8]]])
print(var_arr.ndim)

for i in var_arr:
    for j in i:
        for k in j:
            print(k)

3
1
2
3
4
5
6
7
8


In [20]:
var_arr1 = np.array([[[1,2,3,4],[5,6,7,8]]])

for i in np.nditer(var_arr1):
    print(i)

1
2
3
4
5
6
7
8


In [23]:
var_arr1 = np.array([[[1,2,3,4],[5,6,7,8]]])

for i in np.nditer(var_arr1,flags=['buffered'],op_dtypes=['S']):
    print(i)

b'1'
b'2'
b'3'
b'4'
b'5'
b'6'
b'7'
b'8'


In [24]:
var_arr1 = np.array([[[1,2,3,4],[5,6,7,8]]])

for i,d in np.ndenumerate(var_arr1):
    print(i,d)

(0, 0, 0) 1
(0, 0, 1) 2
(0, 0, 2) 3
(0, 0, 3) 4
(0, 1, 0) 5
(0, 1, 1) 6
(0, 1, 2) 7
(0, 1, 3) 8
