In [1]:
import numpy as np

In [7]:
var = np.array([1,2,3])
co = var.copy()
var[1] = 3   #main diff.
print(co)

[1 2 3]


In [6]:
var1= np.array([1,2,4])
co1 =  var1.view()
var1[1] = 3   #main diff.
print(co1)

[1 3 4]


#Join an array

In [8]:
var_join = np.array([1,2,3,4]) 
var_join1 = np.array([9,8,7,6]) 

var_concat = np.concatenate((var_join,var_join1))
print(var_concat)

[1 2 3 4 9 8 7 6]


In [15]:
var_join2 = np.array([[1,2],[3,4]])
var_join3 = np.array([[9,8],[7,6]])

var_concat2 = np.concatenate((var_join2,var_join3), axis = 0)

print(var_concat2)

[[1 2]
 [3 4]
 [9 8]
 [7 6]]


In [26]:
var_2 = np.array([1,2,3,4])
var_3 = np.array([9,8,7,6])

a_new = np.stack((var_2,var_3),axis=1)
print(a_new)

[[1 9]
 [2 8]
 [3 7]
 [4 6]]


In [24]:
var_2 = np.array([1,2,3,4])
var_3 = np.array([9,8,7,6])

a_new = np.vstack((var_2,var_3)) #column
print(a_new)

[[1 2 3 4]
 [9 8 7 6]]


In [25]:
var_2 = np.array([1,2,3,4])
var_3 = np.array([9,8,7,6])

a_new = np.hstack((var_2,var_3)) #row
print(a_new)

[1 2 3 4 9 8 7 6]


In [27]:
var_2 = np.array([1,2,3,4])
var_3 = np.array([9,8,7,6])

a_new = np.dstack((var_2,var_3))
print(a_new)

[[[1 9]
  [2 8]
  [3 7]
  [4 6]]]


#split the array