1. Consider a NumPy array containing the daily temperatures for a week. How would you find the day with the highest maximum temperature and the day with the lowest minimum temperature?

In [6]:
import numpy as np
temp = np.array([10,18,15,19,20,16,15])
print("Minimum Temprature: ",np.min(temp))
print("Maximum Temprature: ", np.max(temp))

Minimum Temprature:  10
Maximum Temprature:  20


2. Imagine you have a NumPy array containing the coordinates of cities in Nepal. Each row represents a city, with the first column being the latitude and the second column being the longitude. How would you calculate the distance between two specific cities using the Haversine formula?

In [10]:
coordinates = np.array([[27.7172,85.3240],[28.2083,83.9889],[26.4542,87.2797]])
print(coordinates)

[[27.7172 85.324 ]
 [28.2083 83.9889]
 [26.4542 87.2797]]


3.Create a NumPy array containing the squares of the numbers from 1 to 10.

In [18]:
arr_sq = np.arange(1,11)
arr_result = arr_sq ** 2
print(arr_result)

[  1   4   9  16  25  36  49  64  81 100]


Slicing

In [26]:
matrix = np.random.randint(6,size=(5,5))
print(matrix)



[[3 3 3 5 0]
 [4 3 5 1 3]
 [3 2 4 1 1]
 [4 1 1 1 1]
 [5 1 5 3 5]]
[]


In [31]:
print(matrix)
print(matrix[2:5,2:5])

[[3 3 3 5 0]
 [4 3 5 1 3]
 [3 2 4 1 1]
 [4 1 1 1 1]
 [5 1 5 3 5]]
[[4 1 1]
 [1 1 1]
 [5 3 5]]


In [40]:
print(matrix)
print()
print(matrix[2:3,:])

[[3 3 3 5 0]
 [4 3 5 1 3]
 [3 2 4 1 1]
 [4 1 1 1 1]
 [5 1 5 3 5]]

[[3 2 4 1 1]]


In [42]:
print(matrix)
print()
print(matrix[1:4,1:4])

[[3 3 3 5 0]
 [4 3 5 1 3]
 [3 2 4 1 1]
 [4 1 1 1 1]
 [5 1 5 3 5]]

[[3 5 1]
 [2 4 1]
 [1 1 1]]


3.Calculate the mean, median, and standard deviation of a NumPy array containing exam scores.

In [49]:
score = np.array([60,25,55,50,35,40])
mean = np.mean(score)
median = np.median(score)
sd = np.std(score)
print(mean)
print(median)
print(sd)


44.166666666666664
45.0
12.047360245667466


4.Sort a NumPy array of names in alphabetical order.

In [52]:
arrange_array = np.array(['ram','shyam','hari','gita','sita'])
new_array = np.sort(arrange_array)
print(new_array)

['gita' 'hari' 'ram' 'shyam' 'sita']


5.Extract a specific column from a NumPy array (e.g., extract all ages from a dataset).

In [55]:
data_set = np.array([['ram',20,],['hari',19],['Gita',20]])
print(data_set[:,1])


['20' '19' '20']


#Round 2
1.Create a NumPy array containing the squares of the first 15 odd numbers.