In [1]:
 import numpy as np

In [2]:
var_ins = np.array([1,2,3,4])

new_var = np.insert(var_ins,2, 40)
print(new_var)

[ 1  2 40  3  4]


In [3]:
var_ins = np.array([1,2,3,4])

new_var = np.insert(var_ins,(2,4), 40)
print(new_var)

[ 1  2 40  3  4 40]


In [6]:
 var_ins1 = np.array([[1,2,3],[1,2,3]])

new_var1 = np.insert(var_ins1,2, 40,axis=0)
print(new_var1)

[[ 1  2  3]
 [ 1  2  3]
 [40 40 40]]


In [7]:
 var_ins1 = np.array([[1,2,3],[1,2,3]])

new_var1 = np.insert(var_ins1,2, 40,axis=1)
print(new_var1)

[[ 1  2 40  3]
 [ 1  2 40  3]]


In [8]:
var_appen = np.array([1,2,3,4])

new_appen = np.append(var_appen, 6.5)
print(new_appen)

[1.  2.  3.  4.  6.5]


In [10]:
var_del =np.array([1,2,3,4])

new_del = np.delete(var_del, 2)
print(new_del)

[1 2 4]
