In [2]:
import numpy as np
a = np.array([1,2,3])
print(a)

[1 2 3]


In [3]:
a + 2

array([3, 4, 5])

In [4]:
#take a sin
np.sin(a)


array([0.84147098, 0.90929743, 0.14112001])

In [6]:
#####Linear algebra
a = np.ones((2,3))
print(a)

b = np.full((3,2),2)
print(b)

np.matmul(a,b)

[[1. 1. 1.]
 [1. 1. 1.]]
[[2 2]
 [2 2]
 [2 2]]


array([[6., 6.],
       [6., 6.]])

In [7]:
#find determinant
c = np.identity(3)
print(c)
np.linalg.det(c)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


1.0