Matrix

In [4]:
import numpy as np

In [8]:
var_mat = np.matrix([[1,2],[1,2]])
var_mat2 = np.matrix([[2,4],[2,4]])

print(var_mat)
print(type(var_mat))
print()
print(var_mat * var_mat2)
print(var_mat.dot(var_mat2))

[[1 2]
 [1 2]]
<class 'numpy.matrix'>

[[ 6 12]
 [ 6 12]]
[[ 6 12]
 [ 6 12]]


In [10]:
var_mat3 = np.matrix([[1,2,3],[4,5,6]])
print(var_mat3)
print(np.transpose(var_mat3))

[[1 2 3]
 [4 5 6]]
[[1 4]
 [2 5]
 [3 6]]


Inverse

In [13]:
var_mat4 = np.matrix([[1,2],[3,4]])
print(var_mat4)
print()
print(np.linalg.inv(var_mat4))

[[1 2]
 [3 4]]

[[-2.   1. ]
 [ 1.5 -0.5]]


Power

In [17]:
var_mat4 = np.matrix([[1,2],[3,4]])
print(np.linalg.matrix_power(var_mat4,2))
print(np.linalg.matrix_power(var_mat4,0))
print(np.linalg.matrix_power(var_mat4,-1))

[[ 7 10]
 [15 22]]
[[1 0]
 [0 1]]
[[-2.   1. ]
 [ 1.5 -0.5]]


Determinate

In [19]:
var_mat5 = np.matrix([[1,2,3],[3,4,3],[1,2,3]])
print(np.linalg.det(var_mat5))

0.0
